### ISSUE TITLE
Pong game score is -10

### ISSUE THREAD

**Issue by rococopeach** [watts4speed/fast-dqn-caffe#6]
I synced code the following version and built them on Ubuntu 14.04.4.
    Caffe                 commit: ff16f6e43dd718921e5203f640dd57c68f01cdb3
    Fast-dqn-caffe   commit c0f5a76961909dbd6a1439748c30be98091c8bfc 
    ALE 0.5.1

Pong game score average is -10. Original paper dnq takes 20.
It seems something wrong. Do you have any idea?

**Comment by watts4speed** [comment]
Hi Rococopeach,

That's about what I was getting.  I asked hmauskn what he though and he
said he though that muupan got higher.  I've never been able to trace down
what the difference was.

**Comment by rococopeach** [comment]
Thank you for your reply.
I will look this issue, when I have time.
