### ISSUE TITLE
kRawFrameHeight should be 210 instead of 250

### ISSUE THREAD

**Issue by joyousrabbit** [watts4speed/fast-dqn-caffe#9]
Hello, in Environment.h:
static constexpr auto kRawFrameHeight = 250;

But according to ALE manuel, the raw frame height should be 210.

"the current screen, provided in row, column,
then colour channel order (typically yielding 210 × 160 × 3 = 100, 800 entries)."

**Comment by watts4speed** [comment]
Thanks for finding this!  If you submit a PR I'll merge it.  I'd do it but I'm not setup to build currently.

**Comment by joyousrabbit** [comment]
Well this variable is not used at all.
